# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04grpc\"\x07\n\x05\x45mpty\"6\n\x04Note\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x63hat_id\x18\x03 \x01(\t\"\x19\n\x06\x43hatId\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\t2\\\n\x0b\x43hatService\x12(\n\nChatStream\x12\x0c.grpc.ChatId\x1a\n.grpc.Note0\x01\x12#\n\x08SendNote\x12\n.grpc.Note\x1a\x0b.grpc.Emptyb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_NOTE = DESCRIPTOR.message_types_by_name['Note']
_CHATID = DESCRIPTOR.message_types_by_name['ChatId']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Empty)
  })
_sym_db.RegisterMessage(Empty)

Note = _reflection.GeneratedProtocolMessageType('Note', (_message.Message,), {
  'DESCRIPTOR' : _NOTE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Note)
  })
_sym_db.RegisterMessage(Note)

ChatId = _reflection.GeneratedProtocolMessageType('ChatId', (_message.Message,), {
  'DESCRIPTOR' : _CHATID,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.ChatId)
  })
_sym_db.RegisterMessage(ChatId)

_CHATSERVICE = DESCRIPTOR.services_by_name['ChatService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=20
  _EMPTY._serialized_end=27
  _NOTE._serialized_start=29
  _NOTE._serialized_end=83
  _CHATID._serialized_start=85
  _CHATID._serialized_end=110
  _CHATSERVICE._serialized_start=112
  _CHATSERVICE._serialized_end=204
# @@protoc_insertion_point(module_scope)
